# Data Cleansing Step 3

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from pprint import pprint
from datetime import datetime

In [2]:
NYC_Trip_201801 = pd.read_csv("./Resources/Bike_Data/NYC_Citibike/2018/Step_2/NYC_Trip_201801.csv")
NYC_Trip_201801

,trip_duration,start_station_name,end_station_name,bikeid,start_date,start_hour
0,970,W 52 St & 11 Ave,6 Ave & W 33 St,31956,01/01/2018,13
1,723,W 52 St & 11 Ave,8 Ave & W 31 St,32536,01/01/2018,15
2,496,W 52 St & 11 Ave,W 34 St & 11 Ave,16069,01/01/2018,15
3,306,W 52 St & 11 Ave,8 Ave & W 52 St,31781,01/01/2018,15
4,306,W 52 St & 11 Ave,Amsterdam Ave & W 66 St,30319,01/01/2018,18
5,1602,W 52 St & 11 Ave,W 15 St & 7 Ave,30106,01/01/2018,21
6,722,W 52 St & 11 Ave,E 48 St & 3 Ave,32059,01/02/2018,7
7,434,W 52 St & 11 Ave,Broadway & W 49 St,30525,01/02/2018,8
8,366,W 52 St & 11 Ave,9 Ave & W 45 St,27439,01/02/2018,8
9,324,W 52 St & 11 Ave,W 49 St & 8 Ave,30892,01/02/2018,8
10,1155,W 52 St & 11 Ave,Greenwich St & W Houston St,31591,01/02/2018,9
11,1200,W 52 St & 11 Ave,Barrow St & Hudson St,30257,01/02/2018,10
12,732,W 52 St & 11 Ave,W 36 St & 9 Ave,32649,01/02/2018,11
13,600,W 52 St & 11 Ave,Broadway & W 58 St,26964,01/02/2018,12
14,1058,W 52 St & 11 Ave,W 38 St & 8 Ave,32617,01/02/2018,13
15,256,W 52 St & 11 Ave,12 Ave & W 40 St,31095,01/02/2018,13
16,318,W 52 St & 11 Ave,11 Ave & W 41 St,31182,01/02/2018,13
17,694,W 52 St & 11 Ave,W 44 St & 5 Ave,32375,01/02/2018,14
18,604,W 52 St & 11 Ave,W 36 St & 9 Ave,32505,01/02/2018,15
19,724,W 52 St & 11 Ave,8 Ave & W 33 St,19512,01/02/2018,15
20,395,W 52 St & 11 Ave,12 Ave & W 40 St,17881,01/02/2018,15
21,520,W 52 St & 11 Ave,Broadway & W 51 St,31426,01/02/2018,16
22,430,W 52 St & 11 Ave,Broadway & W 51 St,32349,01/02/2018,16
23,842,W 52 St & 11 Ave,8 Ave & W 33 St,31019,01/02/2018,16
24,243,W 52 St & 11 Ave,9 Ave & W 45 St,29984,01/02/2018,16
25,705,W 52 St & 11 Ave,W 41 St & 8 Ave,20922,01/02/2018,16
26,1163,W 52 St & 11 Ave,W 45 St & 6 Ave (OLD),33277,01/02/2018,16
27,680,W 52 St & 11 Ave,8 Ave & W 33 St,16425,01/02/2018,16
28,634,W 52 St & 11 Ave,W 44 St & 5 Ave,28382,01/02/2018,17
29,782,W 52 St & 11 Ave,8 Ave & W 31 St,30649,01/02/2018,17
...,...,...,...,...,...,...
718964,925,North Moore St & Greenwich St,Mercer St & Bleecker St,31396,01/31/2018,15
718965,1186,North Moore St & Greenwich St,W 15 St & 10 Ave,32943,01/31/2018,15
718966,153,North Moore St & Greenwich St,Murray St & West St,17443,01/31/2018,16
718967,194,North Moore St & Greenwich St,Vesey Pl & River Terrace,16746,01/31/2018,16
718968,288,North Moore St & Greenwich St,Vesey Pl & River Terrace,21334,01/31/2018,16
718969,226,North Moore St & Greenwich St,Vesey Pl & River Terrace,16502,01/31/2018,16
718970,246,North Moore St & Greenwich St,Greenwich St & W Houston St,27978,01/31/2018,16
718971,239,North Moore St & Greenwich St,Vesey Pl & River Terrace,19534,01/31/2018,16
718972,154,North Moore St & Greenwich St,Franklin St & W Broadway,31973,01/31/2018,16
718973,797,North Moore St & Greenwich St,Vesey Pl & River Terrace,18335,01/31/2018,16
718974,190,North Moore St & Greenwich St,Barclay St & Church St,25504,01/31/2018,16
718975,297,North Moore St & Greenwich St,Vesey Pl & River Terrace,15080,01/31/2018,17
718976,175,North Moore St & Greenwich St,Hudson St & Reade St,32243,01/31/2018,17
718977,292,North Moore St & Greenwich St,Vesey Pl & River Terrace,18497,01/31/2018,17
718978,622,North Moore St & Greenwich St,Bus Slip & State St,25683,01/31/2018,17
718979,1552,North Moore St & Greenwich St,W 44 St & 5 Ave,17141,01/31/2018,17
718980,222,North Moore St & Greenwich St,Vesey Pl & River Terrace,31796,01/31/2018,17
718981,335,North Moore St & Greenwich St,Liberty St & Broadway,25374,01/31/2018,17
718982,217,North Moore St & Greenwich St,Vesey Pl & River Terrace,32340,01/31/2018,17
718983,900,North Moore St & Greenwich St,North Moore St & Greenwich St,26896,01/31/2018,17
718984,507,North Moore St & Greenwich St,Cliff St & Fulton St_1,26934,01/31/2018,17
718985,528,North Moore St & Greenwich St,Cliff St & Fulton St_1,31483,01/31/2018,17
718986,533,North Moore St & Greenwich St,Cliff St & Fulton St_1,19938,01/31/2018,17
718987,203,North Moore St & Greenwich St,Vesey Pl & River Terrace,28647,01/31/2018,17
718988,739,North Moore St & Greenwich St,Front St & Maiden Ln,33044,01/31/2018,17
718989,843,North Moore St & Greenwich St,Suffolk St & Stanton St,15153,01/31/2018,17
718990,244,North Moore St & Greenwich St,Vesey Pl & River Terrace,26896,01/31/2018,17
718991,302,North Moore St & Greenwich St,Vesey Pl & River Terrace,33111,01/31/2018,18
718992,222,North Moore St & Greenwich St,Lispenard St & Broadway,16675,01/31/2018,18
718993,713,North Moore St & Greenwich St,E 10 St & 5 Ave,17928,01/31/2018,19

In [3]:
NYC_Trip_201801=NYC_Trip_201801.set_index("start_station_name")

# NYC_Trip_201801.groupby(["start_station_name"])

In [5]:
NYC_Trip_201801_analysis = NYC_Trip_201801.groupby(["start_date", "start_station_name", "start_hour"])["trip_duration"].mean()
NYC_Trip_201801_analysis_count = NYC_Trip_201801.groupby(["start_date", "start_station_name", "start_hour"])["trip_duration"].count()

NYC_Trip_201801_analysis = pd.DataFrame(NYC_Trip_201801_analysis).reset_index()
NYC_Trip_201801_analysis.head()

   start_date start_station_name  start_hour  trip_duration
0  01/01/2018   1 Ave & E 110 St           5          459.0
1  01/01/2018   1 Ave & E 110 St          14          760.0
2  01/01/2018    1 Ave & E 16 St           0          153.0
3  01/01/2018    1 Ave & E 16 St           1          323.0
4  01/01/2018    1 Ave & E 16 St           2          184.6

In [7]:
NYC_Trip_201801_analysis_count = pd.DataFrame(NYC_Trip_201801_analysis_count).reset_index()
# NYC_Trip_201801_analysis_count
NYC_Trip_201801_analysis['trip_count'] = NYC_Trip_201801_analysis_count['trip_duration']
NYC_Trip_201801_analysis = NYC_Trip_201801_analysis.rename(columns={"trip_duration": "avg_trip_duration"})
NYC_Trip_201801_analysis['avg_trip_duration'].round()
NYC_Trip_201801_analysis.head()

   start_date start_station_name  start_hour  avg_trip_duration  trip_count
0  01/01/2018   1 Ave & E 110 St           5              459.0           1
1  01/01/2018   1 Ave & E 110 St          14              760.0           1
2  01/01/2018    1 Ave & E 16 St           0              153.0           1
3  01/01/2018    1 Ave & E 16 St           1              323.0           3
4  01/01/2018    1 Ave & E 16 St           2              184.6           5

In [31]:
NYC_Trip_201801_count = NYC_Trip_201801.groupby(["start_hour"])["trip_duration"].count()

NYC_Trip_201801_count

start_hour
0      5163
1      2753
2      1585
3       989
4      1259
5      5505
6     17018
7     36156
8     64041
9     49092
10    31659
11    31528
12    36183
13    39309
14    42309
15    44969
16    51919
17    71400
18    67558
19    44519
20    29593
21    20314
22    15010
23     9163
Name: trip_duration, dtype: int64